# Generated by Django 4.2.19 on 2025-02-20 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_systemsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='counter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counter_orders', to='store.counter'),
        ),
    ]
