# Generated by Django 4.2.19 on 2025-02-21 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_orders_alter_order_counter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='storecounter',
            name='manager',
            field=models.ForeignKey(editable=False, limit_choices_to={'role': 'store_manager'}, on_delete=django.db.models.deletion.CASCADE, related_name='managed_counters', to=settings.AUTH_USER_MODEL),
        ),
    ]
