# Generated by Django 4.2.19 on 2025-02-22 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_customer_alter_customuser_role_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('accountant', 'Accountant'), ('store_manager', 'Store Manager'), ('sales_staff', 'Sales Staff'), ('customer', 'Khách hàng')], default='sales_staff', help_text='Chọn vai trò của người dùng', max_length=20),
        ),
    ]
